### ISSUE TITLE
has_many finds deep elements, not just immediate children

### ISSUE THREAD

**Issue by dmolesUC3** [dam5s/happymapper#60]
Given XML like the following:

```xml
  <qux>
    <foo id="0"/>
    <foo id="1"/>
    <baz>
      <foo id="2"/>
      <foo id="3"/>
    </baz>
  </qux>
```

Mapping this with happymapper, `Qux.foo` should be an array of size 2 containing only the `<foo>s` with IDs 0 and 1, but in fact it's an array of size 4 containing both those and the deeply nested `<foo>s` with IDs 2 and 3, as demonstrated below:

```ruby
#! /usr/bin/env ruby

require 'happymapper'

class Foo
  include HappyMapper

  tag 'foo'

  attribute :id, Integer
end

class Baz
  include HappyMapper

  tag 'baz'

  has_many :foo, Foo
end

class Qux
  include HappyMapper

  tag 'qux'

  has_many :foo, Foo
  element :baz, Baz
end

xml = '
  <qux>
    <foo id="0"/>
    <foo id="1"/>
    <baz>
      <foo id="2"/>
      <foo id="3"/>
    </baz>
  </qux>
'

qux = Qux.parse(xml)

puts 'qux/foo'
qux.foo.each { |f| puts f.id }

puts 'qux/baz/foo'
qux.baz.foo.each { |f| puts f.id }
```

This should print

```
qux/foo
0
1
qux/baz/foo
2
3
```

but instead it prints 

```
qux/foo
0
1
2
3
qux/baz/foo
2
3
```

**Comment by FloFra** [comment]
The default xpath is ```.//``` a.k.a. a greedy one. 

Use ```has_many :foo, Foo, :xpath => '.'``` to get what you want.

**Comment by dmolesUC3** [comment]
You're right, that's [explicitly covered in the readme](https://github.com/dam5s/happymapper#filtering-with-xpath-non-greedy). Apologies.
